services:
  - type: web
    name: directus
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx directus start
    envVars:
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        fromDatabase:
          name: directus-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: directus-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: directus-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: directus-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: directus-db
          property: password
      - key: ADMIN_EMAIL
        value: d.salaffi@rock-island.it
      - key: ADMIN_PASSWORD
        value: comAppy01

databases:
  - name: directus-db
    plan: free
    databaseName: directus
    user: directus
